### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by Emirik9** [ayanamiblhx/nonebot_plugin_setu#8]
启动时报如下错误，请问一下该怎么解决
04-05 02:04:36 [ERROR] nonebot | Failed to import "nonebot_plugin_setu"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/ubuntu/.local/lib/python3.9/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/mybot/MMToubot/./bot.py", line 28, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/home/ubuntu/.local/lib/python3.9/site-packages/nonebot/plugin/load.py", line 119, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/nonebot/plugin/load.py", line 53, in load_all_plugins
    return manager.load_all_plugins()
  File "/home/ubuntu/.local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 128, in load_all_plugins
    return set(
  File "/home/ubuntu/.local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
> File "/home/ubuntu/.local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 104, in load_plugin
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/home/ubuntu/.local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 194, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/.local/lib/python3.9/site-packages/nonebot_plugin_setu/__init__.py", line 31, in <module>
    Config.create_file()
  File "/home/ubuntu/.local/lib/python3.9/site-packages/nonebot_plugin_setu/create_file.py", line 33, in create_file
    os.mkdir('loliconImages/r18')
FileNotFoundError: [Errno 2] No such file or directory: 'loliconImages/r18'

**Comment by ayanamiblhx** [comment]
> 启动时报如下错误，请问一下该怎么解决 04-05 02:04:36 [ERROR] nonebot | Failed to import "nonebot_plugin_setu" Traceback (most recent call last): File "", line 1, in File "/usr/local/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main exitcode = _main(fd, parent_sentinel) File "/usr/local/lib/python3.9/multiprocessing/spawn.py", line 129, in _main return self._bootstrap(parent_sentinel) File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap self.run() File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run self._target(*self._args, **self._kwargs) File "/home/ubuntu/.local/lib/python3.9/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started target(sockets=sockets) File "/home/ubuntu/.local/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run return asyncio.run(self.serve(sockets=sockets)) File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run return loop.run_until_complete(main) File "/home/ubuntu/.local/lib/python3.9/site-packages/uvicorn/server.py", line 67, in serve config.load() File "/home/ubuntu/.local/lib/python3.9/site-packages/uvicorn/config.py", line 458, in load self.loaded_app = import_from_string(self.app) File "/home/ubuntu/.local/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string module = importlib.import_module(module_str) File "/usr/local/lib/python3.9/importlib/**init**.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1030, in _gcd_import File "", line 1007, in _find_and_load File "", line 986, in _find_and_load_unlocked File "", line 680, in _load_unlocked File "", line 850, in exec_module File "", line 228, in _call_with_frames_removed File "/home/ubuntu/mybot/MMToubot/./bot.py", line 28, in nonebot.load_from_toml("pyproject.toml") File "/home/ubuntu/.local/lib/python3.9/site-packages/nonebot/plugin/load.py", line 119, in load_from_toml return load_all_plugins(plugins, plugin_dirs) File "/home/ubuntu/.local/lib/python3.9/site-packages/nonebot/plugin/load.py", line 53, in load_all_plugins return manager.load_all_plugins() File "/home/ubuntu/.local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 128, in load_all_plugins return set( File "/home/ubuntu/.local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 129, in filter(None, (self.load_plugin(name) for name in self.list_plugins()))
> 
> > File "/home/ubuntu/.local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 104, in load_plugin
> > module = importlib.import_module(name)
> > File "/usr/local/lib/python3.9/importlib/**init**.py", line 127, in import_module
> > return _bootstrap._gcd_import(name[level:], package, level)
> > File "", line 1030, in _gcd_import
> > File "", line 1007, in _find_and_load
> > File "", line 986, in _find_and_load_unlocked
> > File "", line 680, in _load_unlocked
> > File "/home/ubuntu/.local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 194, in exec_module
> > super().exec_module(module)
> > File "", line 850, in exec_module
> > File "", line 228, in _call_with_frames_removed
> > File "/home/ubuntu/.local/lib/python3.9/site-packages/nonebot_plugin_setu/**init**.py", line 31, in 
> > Config.create_file()
> > File "/home/ubuntu/.local/lib/python3.9/site-packages/nonebot_plugin_setu/create_file.py", line 33, in create_file
> > os.mkdir('loliconImages/r18')
> > FileNotFoundError: [Errno 2] No such file or directory: 'loliconImages/r18'

已修复此bug，请更新至最新版[1.0.17]使用

**Comment by Emirik9** [comment]
好的，谢谢！
