### ISSUE TITLE
获取涩图报错

### ISSUE THREAD

**Issue by QinCaii** [ayanamiblhx/nonebot_plugin_setu#9]
[ERROR] nonebot_plugin_setu | 
[ERROR] nonebot_plugin_setu | 下载时出现异常

[ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_setu, type=message, priority=1, temp=False> failed.
ssl.SSLSyscallError: Some I/O error occurred (_ssl.c:1129

anyio.BrokenResourceError

httpcore.ConnectError

httpx.ConnectError

nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 2}, 
msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>

**Comment by ayanamiblhx** [comment]
> [ERROR] nonebot_plugin_setu | 
> [ERROR] nonebot_plugin_setu | 下载时出现异常
> 
> [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_setu, type=message, priority=1, temp=False> failed.
> ssl.SSLSyscallError: Some I/O error occurred (_ssl.c:1129
> 
> anyio.BrokenResourceError
> 
> httpcore.ConnectError
> 
> httpx.ConnectError
> 
> nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 2}, 
> msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>

是否配置了代理，如果没有请向机器人发送指令: 关闭魔法或者把代理配置好

**Comment by QinCaii** [comment]
关闭了的，还是一样报错
[WARNING] nonebot_plugin_gocqhttp | [1704523646] 好友消息发送失败: 消息为空.

**Comment by ayanamiblhx** [comment]
> 关闭了的，还是一样报错
> [WARNING] nonebot_plugin_gocqhttp | [1704523646] 好友消息发送失败: 消息为空. 

一次也没下载成功?

**Comment by QinCaii** [comment]
是的

**Comment by ayanamiblhx** [comment]
> 是的

gocq报错信息，nonebot报错信息，还有setu_config.json都发一下

**Comment by QinCaii** [comment]
setu_config.json
{"SUPERUSERS": ["3055146328"], "PROXIES_HTTP": "", "PROXIES_SOCKS": "", "PROXIES_SWITCH": 0, "ONLINE_SWITCH": 1}
gocq报错信息和nonebot报错信息要在哪里看呀

**Comment by ayanamiblhx** [comment]
> setu_config.json
> {"SUPERUSERS": ["3055146328"], "PROXIES_HTTP": "", "PROXIES_SOCKS": "", "PROXIES_SWITCH": 0, "ONLINE_SWITCH": 1}
> gocq报错信息和nonebot报错信息要在哪里看呀

保持gocq和nonebot在前台运行，看看错误日志

**Comment by QinCaii** [comment]
不好意思，我没能理解，我是新手不是很懂，错误日志是一个文件 还是发送指令后指终端里输出的debug信息? 如果是debug信息的话，gocq没有显示，nonebot的话
04-11 19:08:53 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_setu, type=message, priority=1, temp=False>
04-11 19:08:53 [DEBUG] nonebot | Running matcher <Matcher from nonebot_plugin_setu, type=message, priority=1, temp=False>
04-11 19:08:53 [DEBUG] nonebot | Running handler <Dependent call=<function _ at 0x0000023A3DDB68B0>, params=[ModelField(name='bot', type=Bot, required=True), ModelField(name='event', type=Event, required=True)], parameterless=[]>
04-11 19:08:53 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_setu, type=message, priority=1, temp=False> running complete
04-11 19:08:53 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_setu, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", 
line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", 
line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\internal\matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\internal\matcher.py", line 635, in simple_run
    await handler(
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_setu\__init__.py", line 44, in _
    file_name = images[random.randint(0, len(images) - 1)]
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\random.py", line 338, in randint
    return self.randrange(a, b+1)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\random.py", line 316, in randrange
    raise ValueError("empty range for randrange() (%d, %d, %d)" % (istart, istop, width))

**Comment by QinCaii** [comment]
![tmp2CFE](https://user-images.githubusercontent.com/49438338/162729217-d8938887-8721-48ef-beeb-99850295a22d.png)
![tmp34A0](https://user-images.githubusercontent.com/49438338/162729227-2d63e3f9-2696-401b-8b75-8ff6b7d99b1f.png)
![tmp49CF](https://user-images.githubusercontent.com/49438338/162729232-65419a7a-34f6-411a-a464-cc812a9df039.png)
![tmp522C](https://user-images.githubusercontent.com/49438338/162729239-f60acebd-1469-42da-8a1f-6b6dd1f2e11e.png)

**Comment by ayanamiblhx** [comment]
> ![tmp2CFE](https://user-images.githubusercontent.com/49438338/162729217-d8938887-8721-48ef-beeb-99850295a22d.png) ![tmp34A0](https://user-images.githubusercontent.com/49438338/162729227-2d63e3f9-2696-401b-8b75-8ff6b7d99b1f.png) ![tmp49CF](https://user-images.githubusercontent.com/49438338/162729232-65419a7a-34f6-411a-a464-cc812a9df039.png) ![tmp522C](https://user-images.githubusercontent.com/49438338/162729239-f60acebd-1469-42da-8a1f-6b6dd1f2e11e.png)

是否关闭了在线发图，如果是，那么需要本地有图片文件

**Comment by QinCaii** [comment]
开启在线发图仍然有报错TAT

**Comment by ayanamiblhx** [comment]
> 开启在线发图仍然有报错TAT

看看错误日志

**Comment by QinCaii** [comment]
![tmp9402](https://user-images.githubusercontent.com/49438338/162730487-26747e75-6167-41e9-a67d-a7b9bd288353.png)
![tmp9B66](https://user-images.githubusercontent.com/49438338/162730495-fc50ad57-4940-4b6d-ba7d-f3af3dded640.png)
![tmpA0E5](https://user-images.githubusercontent.com/49438338/162730498-d06fd9f5-4944-416c-b6c5-2672ee69417d.png)
![tmpA73F](https://user-images.githubusercontent.com/49438338/162730506-ea7345b4-f7cb-495d-a0cf-1cb018e92303.png)

**Comment by QinCaii** [comment]
但是可以下载涩图了，我虽然没设置代理但是却开了代理，关掉之后就可以下载了，但尽管图库里有涩图，输入setu指令仍然会报错，开启和关闭在线都一样

**Comment by ayanamiblhx** [comment]
> 但是可以下载涩图了，我虽然没设置代理但是却开了代理，关掉之后就可以下载了，但尽管图库里有涩图，输入setu指令仍然会报错，开启和关闭在线都一样

是否开启了涩涩?

**Comment by QinCaii** [comment]
啊，果然可以了，那个难道不是涩图开关???

**Comment by ayanamiblhx** [comment]
> 啊，果然可以了，那个难道不是涩图开关???

普通图片和涩涩图片分开存储，因为开启了涩涩并且本地没有文件导致报错，此为程序bug，将在下个版本进行修复

**Comment by ayanamiblhx** [comment]
> 啊，果然可以了，那个难道不是涩图开关???

目前的方案是开启涩涩模式下载几张图片就能正常使用

**Comment by QinCaii** [comment]
好的，谢谢！

**Comment by ayanamiblhx** [comment]
> 好的，谢谢！

最开始下载图片失败的错误应该是lolicon那边服务器出了问题，目前应该已经修复，请再次检查能否正常使用，若没有其它问题请关闭此issue

**Comment by QinCaii** [comment]
请帮我删除这个issue，谢谢
